## This is the configuration file for Headroom.
## See https://github.com/vaclavsvejcar/headroom for more details.

version: 0.5.0.0

run-mode: add

source-paths:
  - src/
  - upgradescripts/

excluded-paths:
  - '\/internal\/'
  - '\/node_modules\/'
  - '\/lib\/'

exclude-ignored-paths: true

template-paths:
  - .headroom-templates

license-headers:
  php:
    margin-bottom-code: 1
    put-after:
      - '^<\?php$'
    block-comment:
      starts-with: '^\/\*'
      ends-with: '\*\/$'
  js:
    block-comment:
      starts-with: '\/\* \(license-header\)'
      ends-with: '\*\/$'

variables:
  project: 'hores'
  year: '{{ _current_year }}'
  author: 'Adrià Vilanova Martínez'
